site_name: Knowledge Base
theme:
  name: material
  logo: images/brain.svg
  # favicon: images/brain.png

nav:
  - Home: index.md
  - Visual Studio Code: visual-studio-code.md
  - Krita: krita.md
  - Photoshop: photoshop.md
  - Wacom Tipps: wacom.md
  - Youtube.apk patchen : youtube-apk.md